#!/bin/sh

set -e

case $0 in
    *-py3)
	python=python3
	;;
    *)
	python=python2
	;;
esac

cp -a tests $ADTTMP/django-tests
cd $ADTTMP/django-tests

echo "Running “$python ./runtests.py --verbosity 2”"
LC_ALL=C.UTF-8 $python ./runtests.py --verbosity 2 --parallel 1
